### ISSUE TITLE
Signature verification fails for structures with arrays

### ISSUE THREAD

**Issue by wingedfox** [exonum/exonum-client#106]
Hello,

When I define transaction with a vector of structures, that in turn contain another vectors I get 'Signature verification failed' error. Passing serialized JSON string in place of inner vectors solves the problem.

Here's the sources of a service and client:
* https://pastebin.com/K4DzcpxS
* https://pastebin.com/akfGmEJc

To reproduce the bug just uncomment the vectors in the both client and service.

**Comment by KateNegrienko** [comment]
Thank you, we're working on it

**Comment by KateNegrienko** [comment]
@wingedfox We fix your problem, please update your exomun-client to 0.10.1 version. 
If the problem returns, let me know

**Comment by wingedfox** [comment]
@KateNegrienko it works like a charm, thank you!
