### ISSUE TITLE
404 error at explorer response

### ISSUE THREAD

**Issue by aleksraiden** [exonum/exonum-client#122]
Hi, 

In our tests, some request to explorer after transaction sending, are returned with http code 404 and body data.type = 'unknown'.  
But in client code we has'nt catch block to check this behaviors, current code checking only if this body returned with 200 Ok code. 

Maybe this code will be ok? [https://github.com/CoinIndexAgency/exonum-client/commit/621c884565aa26779e5f4e22fa65fc3779c64397](url)

**Comment by boguslavsky** [comment]
Hi @aleksraiden.

Explorer API [has been changed](https://github.com/exonum/exonum/blob/master/CHANGELOG.md#090---2018-07-19) in Exonum 0.9.

Briefly:
> New API implementation supports only query parameters in GET requests. In this way requests like GET api/my_method/:first/:second should be replaced by the GET api/my_method?first=value1&second=value2

Here an example of how explorer API requests should looks now:
- get blocks (no changes): `/api/explorer/v1/blocks?count=${count}&latest=${latest}`
- get block: `/api/explorer/v1/block?height=${height}`
- get transaction: `/api/explorer/v1/transactions?hash=${hash}`

If you are using `Exonum.send()` method of latest light client library but your core is outdated - just install pervious version of light client. Find compatibility table at the top of [README](https://github.com/exonum/exonum-client).

Please let us know if this helped.

P.S.: Sorry but code you provided is not publicly accessible.

**Comment by aleksraiden** [comment]
Sorry, linked private repo. [https://gist.github.com/aleksraiden/7872c52ad5251f2bc53fd709fe838d95](url)

No, problem isn't at GET/POST query. Our test platform use latest core and client code. 

At client (method Exonum.send) we send first query with new transaction and second, pooling explorer to obtain status of the transaction. And we have situation, if we try to check latest transaction status, core returned 404 Not found HTTP status code (but client code expects 200 OK) - code at line 69 newer be executed. And promise hasn't catch block. In this case no next attempts to check status - exception returned immediately. As I modify code and increase attempt counter at this case too - all ok.  See lines 74..81

**Comment by boguslavsky** [comment]
@aleksraiden can you please check access rights on your gist file, it seems to be still private...

**Comment by boguslavsky** [comment]
Ok, I understand now.
Thank you for the report 👍
We will cover this case very soon.

**Comment by aleksraiden** [comment]
Lot of thanks! Great work!

**Comment by boguslavsky** [comment]
@aleksraiden Hi! Find update `Exonum.send` method in v0.12.2.
Now it ignores invalid and error node responses.
