### ISSUE TITLE
Can I disable check transaction status after send?

### ISSUE THREAD

**Issue by aleksraiden** [exonum/exonum-client#123]
In some case, e.g. if we created long-timed block (5 - 10 min or min 100+ transaction per block), current client isn't good way to sending transaction. If big block (or long timeout) we haven't transaction status "committed" as long, as we collected data at mempool. But current logic create periodical check status.

May be we can disable query to explorer api? In example, set explorerBasePath (in send function) to Null or attempts counter to 0? With this we can send more transaction per second (and with less memory usage) from one client too.

**Comment by boguslavsky** [comment]
@aleksraiden Good catch. Thank you for you idea.
Please check latest v0.12.2. Now it is possible to set attempts to `0` to avoid sending requests to explorer.
Also please note that order of `timeout` and `attempts` parameters is changed. Now `attempts` goes first.
