### ISSUE TITLE
Publish as npm package

### ISSUE THREAD

**Issue by boguslavsky** [exonum/exonum-client#18]
Currently published as private package: https://www.npmjs.com/package/@exonum/exonum-client.
Need to make public on release.

**Comment by slowli** [comment]
Almost done. I'd label the commit that was published to `npm` with `v0.1.0`. Notice that `npm version` can do this automatically, and that Travis can automatically publish to npm on tagged commits.

**Comment by boguslavsky** [comment]
Implemented deploying to `npm` via `Travis` in #54.
