### ISSUE TITLE
Uniform coding style?

### ISSUE THREAD

**Issue by slowli** [exonum/exonum-client#3]
It could be beneficial to use a uniform coding style for all JS projects. I like [semistandard](https://www.npmjs.com/package/semistandard) (it is currently used in [pwbox][pwbox]), although it is a subject of discussion. Such a tool can also be used as a linter, which is necessary for writing quality code.

[pwbox]: https://github.com/exonum/pwbox

**Comment by qvantor** [comment]
https://github.com/exonum/exonum-client/pull/64
