### ISSUE TITLE
Exonum datatypes interface and newType()

### ISSUE THREAD

**Issue by slowli** [exonum/exonum-client#6]
The current definition of Exonum datatypes works, but it can probably be improved as follows.

Each datatype has a set of methods
```javascript
DataType.prototype = {
  serialize: function () {
    // serializes the value as Uint8Array
  },
  hash: function () {
    // calculates the hash of the serialized data
    // internally, simply calls nacl's hash on this.serialize()
  },
  isFixedLength: function () {
    // Whether the datatype has fixed byte length. It determines how the fields of this type
    // are (de)serialized as fields of other types
  }
};
Datatype.deserialize = function (bytes) {
  // deserializes the value from Uint8Array
};
```
Example:
```javascript
// Built-in types
var x = new exonum.types.Uint8(120);
x.serialize(); // === Uint8Array([ 120 ])
x.hash(); // === exonum.types.Hash([ ... ])
var y = exonum.types.Uint8.deserialize(new Uint8Array([ 125 ]));
// Constructed types
var SomeType = exonum.types.newType({ /* type spec */ });
var z = new SomeType(/* initializer; TBD */);
z.serialize();
z.hash();
SomeType.deserialize(new Uint8Array([ /* ... */ ]));
```
This interface could be especially useful for datatypes constructed with `newType()`, but it could work for primitive/predefined datatypes for consistency.

Possible problems/topics for discussion:
  * Primitive integer datatypes cease to behave like integers. For example, `x + y` in the example above will cease working properly (although it could be partially brought back by defining the `valueOf` method). But it may be a good thing; we probably wouldn't want to allow arbitrary operations on datatypes. Raw values could be extracted from primitive types in a uniform fashion, e.g., via `raw` property.
  * `deserialize` may double as a constructor: If the constructor is supplied with a `Uint8Array`, then deserialization is performed. Note that this will work for hashes, pubkeys and signatures.
  * `newType()` should be discussed in detail in another issue; I feel that its interface is not optimal either

**Comment by boguslavsky** [comment]
@slowli can we close this issue due Exonum had migrated to protobuf?

**Comment by slowli** [comment]
Sure.
