### ISSUE TITLE
Exonum v0.2 compatibility?

### ISSUE THREAD

**Issue by Ralvke** [exonum/exonum-client#68]
Hi

I am used this ["template"](https://github.com/exonum/exonum-client/issues/59#issuecomment-327770639) and all works, but update of `exonum-client` breaks compatibility ("Unable to verify transaction") for all `exonum` versions (0.2, 0.1.1) (my code isn't changed)

With what version is the client compatible now?

**Comment by Ralvke** [comment]
Its problem in `0.2.1` version of client
`0.2.0` works fine with Exonum `0.2`

**Comment by boguslavsky** [comment]
Hi @Ralvke.
Syntax in ["template"](https://github.com/exonum/exonum-client/issues/59#issuecomment-327770639) is still correct.
Most likely this bug appeared after serialization refactoring in `0.2.1`.
We will look into the problem and keep you updated.
Thank you for your report.

**Comment by boguslavsky** [comment]
@Ralvke please update to `0.2.2`.
Issue was fixed in https://github.com/exonum/exonum-client/commit/7fe303da4f6787da67028d06f576847351247562.
