### ISSUE TITLE
Type specifications

### ISSUE THREAD

**Issue by slowli** [exonum/exonum-client#7]
Type specifications right now are quite redundant. While such specs might make sense in Rust, they could be improved in JavaScript to look like
```javascript
[
  { name: 'foo', type: types.Uint8 },
  { name: 'bar', type: types.String },
  { name: 'bazz', type: SomeCustomType }
]
```

**Future compatibility.** Note that types declared in this way are *sequences*; besides them, we might define other compositions in the future (e.g., enums, optional types, arrays, and/or `Any`). They can be straightforwardly defined though related constructions, e.g.,
```javascript
{
  oneOf: [
    types.Uint32,
    types.String
  ]
}
```
for enums, `{ array: types.Uint32 }` for arrays, etc. Thus, we probably shouldn't worry about specification extensions right now.

**Comment by boguslavsky** [comment]
Implemented in 0.6.0
